FROM bitnami/tomcat:9.0.41-debian-10-r0
COPY ROOT.war /opt/bitnami/tomcat/webapps_default
#COPY --chown=root:root server.xml /opt/bitnami/tomcat/conf
#RUN chmod 777 /opt/bitnami/tomcat/conf/server.xml